# NOTE:
# This job didn't work.  However, exec'ing into the minio container then setting the alias and creating the buckets did

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "stoat.fullname" . }}-create-buckets-{{ now | date "20060102150405" }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoat.labels" . | nindent 4 }}
    stoat-app: create-buckets
  {{- with .Values.global.all.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:

  template:
    metadata:
      labels:
        stoat-app: create-buckets
        {{- include "stoat.labels" . | nindent 8 }}
        {{- with .Values.web.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: create-buckets
          image: docker.io/minio/minio
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - |
              echo http://{{ .Release.Name }}-minio:9000
              while ! /usr/bin/mc ready minio; do
                /usr/bin/mc alias set minio http://{{ .Release.Name }}-minio:9000 minioautumn minioautumn
                echo 'Waiting minio...' && sleep 1
              done
              /usr/bin/mc mb minio/stoat-uploads
              exit 0
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

